# Generated by Django 5.2.1 on 2025-05-19 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("deleted", "Deleted"),
                            ("archived", "Archived"),
                            ("suspended", "Suspended"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("grade_level", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "parent_guardian_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parent_guardian_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("academic_interests", models.TextField(blank=True, null=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("deleted", "Deleted"),
                            ("archived", "Archived"),
                            ("suspended", "Suspended"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("bio", models.TextField(blank=True, null=True)),
                ("qualifications", models.TextField(blank=True, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
            },
        ),
    ]
