name: Close Issues on Merge

on:
  pull_request:
    types:
      - closed  # Triggers when a PR is merged or closed

jobs:
  close-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Issue References
        id: extract-issues
        run: |
          # Extract issue references from the PR body (e.g., "Fixes #123" or "Closes #456")
          echo "PR_BODY=${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo "ISSUE_REFS=$(echo ${{ github.event.pull_request.body }} | grep -oE '#[0-9]+' | tr -d '#')" >> $GITHUB_ENV

      - name: Close Issues
        if: env.ISSUE_REFS
        run: |
          for ISSUE in $ISSUE_REFS; do
            echo "Closing issue #$ISSUE"
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE \
              -d '{"state": "closed"}'
          done
